import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import Footer from "@/components/Footer";

const SpaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Foordle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={SpaceGrotesk.className}>
          <header className='xl:mx-auto max-w-6xl sm:mx-10 mx-4 flex justify-between py-8'>
            <h1 className='text-2xl font-bold text-emerald-400'>Foordle ⚽</h1>
            <SignedOut>
              <SignInButton />
            </SignedOut>

            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          
          <main>
            <div className='max-w-6xl flex justify-center items-center mx-auto'>
              {children}
            </div>
          </main>

          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
